### ISSUE TITLE
Better login

### ISSUE THREAD

**Issue by sonder-joker** [sonder-joker/mirai-compose#11]
更友好的登录体验，让用户无需打开浏览器即可登录

**Comment by Nambers** [comment]
发现了一些问题 #20

**Comment by sonder-joker** [comment]
并不是很好实现，予以低优先级

**Comment by Nambers** [comment]
Catch the error throwing in login procession or the error will make entire program unexpect exited.
like:
![image](https://user-images.githubusercontent.com/35139537/124213545-5917c380-db23-11eb-87f5-13c28720c4ac.png)
