### ISSUE TITLE
不支持滑动输入框，请安装solver

### ISSUE THREAD

**Issue by nativejie** [sonder-joker/mirai-compose#49]
![image](https://user-images.githubusercontent.com/31497228/118661258-88979880-b821-11eb-9801-a126ca6dbca7.png)

**Comment by nativejie** [comment]
请问这个应该怎么解决 Window版

**Comment by Nambers** [comment]
> 请问这个应该怎么解决 Window版

已补充到首页文档
![image](https://user-images.githubusercontent.com/35139537/118766327-dc03f800-b8ae-11eb-8c43-28f7124cd962.png)
在https://github.com/project-mirai/mirai-login-solver-selenium#%E6%89%8B%E5%8A%A8%E4%B8%8B%E8%BD%BD这下载然后放到plugin目录

**Comment by nativejie** [comment]
> > 请问这个应该怎么解决 Window版
> 
> 已补充到首页文档
> ![image](https://user-images.githubusercontent.com/35139537/118766327-dc03f800-b8ae-11eb-8c43-28f7124cd962.png)
> 在https://github.com/project-mirai/mirai-login-solver-selenium#%E6%89%8B%E5%8A%A8%E4%B8%8B%E8%BD%BD 这下载然后放到plugin目录

把源文件放进去 还是要打包一下？

**Comment by Nambers** [comment]
> > > 请问这个应该怎么解决 Window版
> 
> > 
> 
> > 已补充到首页文档
> 
> > ![image](https://user-images.githubusercontent.com/35139537/118766327-dc03f800-b8ae-11eb-8c43-28f7124cd962.png)
> 
> > 在https://github.com/project-mirai/mirai-login-solver-selenium#%E6%89%8B%E5%8A%A8%E4%B8%8B%E8%BD%BD 这下载然后放到plugin目录
> 
> 
> 
> 把源文件放进去 还是要打包一下？
> 
> 

从https://maven.aliyun.com/repository/public/net/mamoe/mirai-login-solver-selenium/1.0-dev-17/mirai-login-solver-selenium-1.0-dev-17-all.jar -o mirai-login-solver-selenium-1.0-dev-17.jar 下载然后放进去

**Comment by AtgetRohman** [comment]
在安装jar包后依旧无法登陆，持续提示密码错误
![image](https://user-images.githubusercontent.com/68192143/123197033-7faf7c00-d4dd-11eb-88a3-65214073a685.png)

**Comment by sonder-joker** [comment]
> 在安装jar包后依旧无法登陆，持续提示密码错误
> ![image](https://user-images.githubusercontent.com/68192143/123197033-7faf7c00-d4dd-11eb-88a3-65214073a685.png)
> 
> 

能提供一下复现环境么 另外有尝试论坛里提供的新方法获取device.json么，可以试一下然后放进相应的文件夹内，如果还有问题还请继续报告

**Comment by Nambers** [comment]
> 在安装jar包后依旧无法登陆，持续提示密码错误
> ![image](https://user-images.githubusercontent.com/68192143/123197033-7faf7c00-d4dd-11eb-88a3-65214073a685.png)

现在mirai-login-solver-selenium已经失效，可以删掉了, 可以参考<https://github.com/project-mirai/mirai-login-solver-selenium>使用手动方法或者TxCaptchaHelper

**Comment by sonder-joker** [comment]
已经解决了，滑动验证码现在是以link弹窗的形式展现
