### ISSUE TITLE
指定登录协议

### ISSUE THREAD

**Issue by Mill413** [sonder-joker/mirai-compose#53]
希望登陆时能指定登录协议登录

**Comment by sonder-joker** [comment]
同mirai console一样，可以在配置文件中选择
未来将会以ui形式加强

**Comment by sonder-joker** [comment]
https://github.com/sonder-joker/mirai-compose/commit/f5a9d2cb653204bfcdbf5b1e278a34d3fc30da5c 中实现（鸽子终于加上了了

**Comment by sonder-joker** [comment]
在v1.1.5以后都可以选择协议
