### ISSUE TITLE
滑动验证码无法复制

### ISSUE THREAD

**Issue by Nambers** [sonder-joker/mirai-compose#59]
**原文**
https://mirai.mamoe.net/topic/215/mirai-compose-%E8%B7%A8%E5%B9%B3%E5%8F%B0%E5%9B%BE%E5%BD%A2%E5%8C%96%E7%9A%84mirai-console%E5%AE%A2%E6%88%B7%E7%AB%AF/12
**预期行为**
弹出滑块验证码地址复制并进入浏览器处理
**实际行为**
无法复制地址(通过ctrl+c)
**版本**
- mirai-compose: `v0.1.0-dev1`

**推测原因**
0.1.0-dev1还在使用mirai-login-solver-selenium插件(现在已经失效
或者0.1.0-dev1的compose还有一些unexpect的bug

**复现**
在master最新分支无法复现, 均报错(见https://github.com/sonder-joker/mirai-compose/issues/11#issuecomment-872674783
在0.1.0-dev1中，滑块表现正常(为弹出一个chrome窗口进行滑块且自动关闭跳转回去)，不过无法登录显示密码错误
手动方法暂未测试
@Zzz2333

**Comment by Zzz2333** [comment]
就是这里不能复制
![image](https://user-images.githubusercontent.com/28297857/124215888-85cdda00-db27-11eb-87c2-4f407841479a.png)
原来这个是会自动弹出chrome窗口的嘛，那我这里也弹出不了。
操作系统：Win10

**Comment by Zzz2333** [comment]
日志中未见异常。然后我复制日志中的地址到浏览器打开，显示一片空白，未出现滑动验证码。浏览器控制台，除了一个看起来无关紧要的报错，也未见到其它有价值的信息。
![image](https://user-images.githubusercontent.com/28297857/124216189-3b992880-db28-11eb-9973-fbcc5776faf7.png)

**Comment by sonder-joker** [comment]
见#49
