### ISSUE TITLE
异常报告

### ISSUE THREAD

**Issue by arily** [sonder-joker/mirai-compose#66]
**简要说明出现的异常**
无法运行

**复现步骤(触发条件)**
无
**日志截图或内容**
![image](https://user-images.githubusercontent.com/10007589/150826858-daceb7fb-13de-4f8c-af7a-46c5d2ed9b83.png)

**环境信息**
- OS: `macOS`, intel芯片
- Version `11.6`

**Comment by sonder-joker** [comment]
这个应该是由于mac没有signature的原因（要钱），建议由自己clone下来build，可以参考一下https://github.com/JetBrains/compose-jb/tree/master/tutorials/Native_distributions_and_local_execution
后续应该会提供jar的版本
