### ISSUE TITLE
Better log system

### ISSUE THREAD

**Issue by sonder-joker** [sonder-joker/mirai-compose#8]
目前的日志系统实现并不是很完善，需要进一步的修改，以及对于全局异常进行更加友好的提示

**Comment by Nambers** [comment]
- 增加右键菜单以支持复制日志片段?
- 导出功能(如果有必要的话

**Comment by sonder-joker** [comment]
1.支持复制粘贴
2.在compose/log文件下
但以上问题仍需进一步优化

**Comment by Nambers** [comment]
- event windows
- log windows filter
- online error report

**Comment by sonder-joker** [comment]
#24
